/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/21f4354a-0e10-4987-b344-14fdd707cbf2

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float humidity;
  float temperature;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include <DHT.h>

#include "driver/adc.h"
#include "esp_adc_cal.h"

#include <ThingerESP32.h>

/* Sleep Time */
#define HOUR_TO_SLEEP 2ULL                        /* Sleep time between each measurement  */
#define uS_TO_S_FACTOR 1000000                    /* Conversion factor for micro seconds to seconds */
#define TIME_TO_SLEEP (HOUR_TO_SLEEP * 60 * 60)  /* Time ESP32 will go to sleep (in seconds) */

/* DHT */
#define DHT_PIN 13
#define DHT_TYPE DHT22

/*  ----------- ADC ------------ 
    ADC1_CHANNEL_0 = 0,  ADC1 channel 0 is GPIO36 
    ADC1_CHANNEL_1,      ADC1 channel 1 is GPIO37 
    ADC1_CHANNEL_2,      ADC1 channel 2 is GPIO38 
    ADC1_CHANNEL_3,      ADC1 channel 3 is GPIO39 
    ADC1_CHANNEL_4,      ADC1 channel 4 is GPIO32 
    ADC1_CHANNEL_5,      ADC1 channel 5 is GPIO33 
    ADC1_CHANNEL_6,      ADC1 channel 6 is GPIO34 
    ADC1_CHANNEL_7,      ADC1 channel 7 is GPIO35 
*/
#define ADC_PIN 32
#define ADC_CHANNEL ADC1_CHANNEL_4
#define ADC_BITS  12                     // 12 bits for esp32
#define ADC_MAX  (pow(2,ADC_BITS) - 1)  // Maximum of the output ADC raw digital reading result, which is 4095 under Single Read mode, 4095 under Continuous Read mode.
#define V_MAX_ADC   2.450  // Maximum measurable input analog mili voltage see  "https://docs.espressif.com/projects/esp-idf/en/v4.4/esp32/api-reference/peripherals/adc.html"

/* ----- Batterie --------- */
#define COEF_PDT 0.33
#define V_BATTERIE_MAX  4.2 * COEF_PDT 
#define V_BATTERIE_MIN  3.3 * COEF_PDT
#define BATTERIE_MAX (V_BATTERIE_MAX / (V_MAX_ADC / ADC_MAX))
#define BATTERIE_MIN (V_BATTERIE_MIN / (V_MAX_ADC / ADC_MAX))


DHT dht(DHT_PIN, DHT_TYPE);
ThingerESP32 thing(USERNAME, DEVICE_ID, DEVICE_CREDENTIAL);

float batterie_percent;
int endpointUpperFlag = 1;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);
  thing.add_wifi(SSID, SSID_PASSWORD);
  
  dht.begin();

  adc1_config_channel_atten(ADC_CHANNEL, ADC_ATTEN_DB_11);  //   ADC_ATTEN_DB_11 --> 150 ~ 2450 (mv)

  int adc_val = analogRead(ADC_PIN);
  batterie_percent = map(adc_val, BATTERIE_MIN , BATTERIE_MAX, 0 ,100);

  thing["dht22"] >> [batterie_percent](pson& in){ 
    in["temperature"] = dht.readTemperature();
    in["humidity"] = dht.readHumidity();
    in["batterie"] = batterie_percent;
  };
  thing["batterie"] >> [](pson& in) {
    in["percent"] = batterie_percent;
    in["device"] = DEVICE_ID;
  };

  esp_sleep_enable_timer_wakeup(TIME_TO_SLEEP * uS_TO_S_FACTOR);  // Timer for the wakeup of the ESP
  
}

void loop() {
  thing.handle();
  thing.write_bucket("dht22","dht22");
  
  if(batterie_percent <= 20.0 && endpointUpperFlag){  
    thing.call_endpoint("dht22_batterie",thing["batterie"]);
    endpointUpperFlag=0;
  }

  delay(500);
  esp_deep_sleep_start();
}




